version: '3.7'

services:
  app_mysql:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
        - "${MYSQL_PORT}:3306"

  mailhog:
    image: mailhog/mailhog
    ports:
        - "${MAILHOG_SMTP_PORT}:1025"
        - "${MAILHOG_HTTP_PORT}:8025"

  elasticsearch:
    image: elastic/elasticsearch:7.8.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
        - "${ES_REQUEST_PORT}:9200"
        - "${ES_COMM_PORT}:9300"
