version: '3.7'

networks:
    shopware:

services:
  app_mysql:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
        - "${MYSQL_PORT}:3306"

  cypress:
    image: cypress/included:5.6.0
    tty: true
    ipc: host
    environment:
      - CYPRESS_baseUrl=http://docker.vm:8000
      - DISPLAY
    volumes:
      - ./tests/e2e:/e2e
      # for Cypress to communicate with the X11 server pass this socket file
      # in addition to any other mapped volumes
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: /bin/bash

  mailhog:
    image: mailhog/mailhog
    ports:
        - "${MAILHOG_SMTP_PORT}:1025"
        - "${MAILHOG_HTTP_PORT}:8025"

  elasticsearch:
    image: elastic/elasticsearch:7.8.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
        - "${ES_REQUEST_PORT}:9200"
        - "${ES_COMM_PORT}:9300"
